---
- name: Remove VM traffic mirroring and DPI bridge configuration
  hosts: proxmox-hosts
  become: true
  vars_files:
    - config.yml

  tasks:
    - name: Run mirror cleanup playbook
      import_playbook: mirror_cleanup.yml

    - name: Remove DPI bridge and veth configuration
      include_tasks: tasks/dpi-monitor-cleanup.yml