- name: Mirror VM traffic from vmbr0 to brdpi using veth and tc
  hosts: proxmox-hosts
  become: true
  vars:
    dest_bridge: "brdpi"
    mirror_target: "veth0"
    tap_prefix: "mirror-tap"
    # List of monitoring VM IDs to exclude for traffic mirroring
    monitor_vm_ids:
      - "401"
    #  - "402"
      
  tasks:

    # # Step 1: Ensure veth0 is configured and attached to br-dpi
    # - name: Check if veth0 is configured in /etc/network/interfaces
    #   shell: grep -A 3 "iface {{ mirror_target }}" /etc/network/interfaces || true
    #   register: veth_config

    # - name: Add veth0 configuration to /etc/network/interfaces if missing
    #   blockinfile:
    #     path: /etc/network/interfaces
    #     marker: "# {mark} ANSIBLE MANAGED BLOCK - veth0 for mirroring"
    #     block: |
    #       auto {{ mirror_target }}
    #       iface {{ mirror_target }} inet manual
    #           bridge_ports none
    #           bridge_stp off
    #           bridge_fd 0
    #           bridge_maxwait 0
    #           bridge_slave yes
    #           bridge_master {{ dest_bridge }}
    #   when: "'iface ' ~ mirror_target not in veth_config.stdout"

    # - name: Bring up veth0 interface
    #   shell: ip link set {{ mirror_target }} up
    #   ignore_errors: true

    # Step 2: Discover tap interfaces dynamically
    - name: Discover tap interfaces for mirroring
      include_tasks: tasks/tap-discover.yml

    - name: Debug list of discovered tap interfaces
      debug:
        msg: "Tap interfaces to process: {{ tap_interfaces }}"

    - name: Skip mirroring setup if no tap interfaces are found
      debug:
        msg: "No tap interfaces found for mirroring. Skipping setup."
      when: tap_interfaces | length == 0

    # Step 3: Apply mirroring to each tap interface
    - name: Set up mirroring for each tap interface
      include_tasks: tasks/mirror-task.yml
      loop: "{{ tap_interfaces }}"
      loop_control:
        loop_var: tap_if
      when: tap_interfaces | length > 0
