- name: Cleanup tc mirror rules created by mirror_vmbr0_to_brdpi.yml
  hosts: proxmox-hosts
  become: true
  vars:
    dest_bridge: "brdpi"
    mirror_target: "veth0"
    # List of monitoring VM IDs to exclude for traffic mirroring
    monitor_vm_ids:
      - "401"
    #  - "402"

  tasks:

    # Step 1: Discover only the tap interfaces connected to vmbr0
    - name: Discover tap interfaces for cleanup
      include_tasks: tasks/tap-discover.yml

    - name: Debug discovered tap interfaces
      debug:
        msg: "Cleaning up tc rules for: {{ tap_interfaces }}"

    # Step 2: Run cleanup only for interfaces that were mirrored
    - name: Run cleanup for each mirrored tap interface
      include_tasks: tasks/mirror-cleanup.yml
      loop: "{{ tap_interfaces }}"
      loop_control:
        loop_var: tap_if
      when: tap_interfaces | length > 0
