---
- name: Setup TAP interface on Proxmox to perform nDPI monitoring
  hosts: proxmox-hosts
  become: true

  tasks:
    - name: Install iproute2 package
      apt:
        name: iproute2
        state: present

    - name: Create tapmon0 interface
      command: ip tuntap add mode tap tapmon0
      args:
        creates: /sys/class/net/tapmon0

    - name: Bring tapmon0 interface UP
      command: ip link set tapmon0 up

    - name: Set tapmon0 interface to promiscuous mode
      command: ip link set tapmon0 promisc on

    - name: Copy tc-mirror.sh to /usr/local/bin
      copy:
        src: files/tc-mirror.sh
        dest: /usr/local/bin/tc-mirror.sh
        mode: '0755'

    - name: Copy tc-mirror-cleanup.sh to /usr/local/bin
      copy:
        src: files/tc-mirror-cleanup.sh
        dest: /usr/local/bin/tc-mirror-cleanup.sh
        mode: '0755'

    - name: Copy tc-mirror.service to /etc/systemd/system
      copy:
        src: files/tc-mirror.service
        dest: /etc/systemd/system/tc-mirror.service
        mode: '0644'

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable and start tc-mirror.service
      systemd:
        name: tc-mirror.service
        enabled: true
        state: started

    - name: Add vmbr99 bridge configuration to /etc/network/interfaces
      blockinfile:
        path: /etc/network/interfaces
        block: |
          auto vmbr99
          iface vmbr99 inet manual
              bridge_ports tapmon0
              bridge_stp off
              bridge_fd 0
        insertafter: EOF

    - name: Bring vmbr99 interface UP
      command: ip link set vmbr99 up

    - name: Set vmbr99 interface to promiscuous mode
      command: ip link set vmbr99 promisc on

    - name: Restart networking service
      service:
        name: networking
        state: restarted