
# TODO: Integrate with edgesec-REST API for IPAM pool management
# TODO: Integrate with Netbox for IPAM pool/host registration
# TODO: Integrate with Datto RMM for IPAM device onboarding
# roles/ipam/tasks/main.yml

- name: Register IPAM pools in Proxmox
  community.general.proxmox_ipam:
    pool: "{{ item.name }}"
    cidr: "{{ item.cidr }}"
    gateway: "{{ item.gateway }}"
  loop: "{{ ipam_pools }}"
  tags:
    - ipam
    - verify_ipam
