- name: Deploy Vault using Docker Compose
  hosts: docker-hosts
  become: true
  tasks:
    - name: Copy docker-compose.yml to remote host
      copy:
        src: docker-compose.yml
        dest: /home/ansible/docker-compose.yml
        owner: ansible
        group: ansible
        mode: '0644'

    - name: Run docker-compose up
      shell: |
        docker-compose -f /home/ansible/docker-compose.yml up -d
      args:
        chdir: /home/ansible