version: '3.7'
services:
  vault:
    image: hashicorp/vault:1.15.2
    container_name: edgesec-vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_ADDR: "http://0.0.0.0:8200"
    volumes:
      - vault-data:/vault/data
    cap_add:
      - IPC_LOCK
    command: server -dev -dev-root-token-id=root
volumes:
  vault-data:
