---
# Playbook: establish_fabric.yml
# Description: Sets up overlay networks, BGP, VXLAN, etc. across nodes
# Usage: ansible-playbook -i ../../inventory establish_fabric.yml


- name: Establish SDN fabric
  hosts: proxmox
  become: yes
  gather_facts: yes
  roles:
    - role: vxlan
    - role: bgp
    - role: nftables
