---
# Playbook: preflight_connectivity.yml
# Description: Verifies connectivity to remote nodes after provisioning
# Usage: ansible-playbook -i ../../inventory preflight_connectivity.yml


- name: Preflight connectivity check
  hosts: proxmox
  become: yes
  gather_facts: yes
  roles:
    - role: preflight
    - role: nftables
