---
# Phase 2: Connectivity Check - Verify reachability between nodes before fabric finalization
- name: Preflight connectivity verification for SDN fabric
  hosts: proxmox_nodes
  become: true

  roles:
    - preflight
