---
# Defaults for ovn-prereqs role
apt_update: true
ovn_prereq_packages:
  - openvswitch-switch
  - ovn-central
  - ovn-host
  - python3-openvswitch

# Whether to stop and mask distro OVN systemd units (useful for running independent stack)
mask_ovn_systemd_units: true
ovn_distro_units:
  - ovn-central
  - ovn-host
