# Phase 2: Connectivity Check - Verify reachability between nodes before fabric finalization

- name: Ping all Proxmox nodes for connectivity verification
  ansible.builtin.ping:
  register: ping_results
  ignore_unreachable: true

- name: Display ping results
  ansible.builtin.debug:
    msg: "Node {{ inventory_hostname }}: {{ 'reachable' if ping_results.ping is defined else 'unreachable' }}"

- name: Check FRR BGP session status on all nodes
  ansible.builtin.command: vtysh -c "show bgp summary"
  register: bgp_status
  changed_when: false
  ignore_errors: true
  when: "'frr' in group_names or 'bgp' in group_names"

- name: Display BGP status
  ansible.builtin.debug:
    msg: |
      BGP Status on {{ inventory_hostname }}:
      {{ bgp_status.stdout | default('FRR not available or BGP not configured') }}
  when: bgp_status is defined

- name: Verify network interfaces are up
  ansible.builtin.command: ip -br link show
  register: interface_status
  changed_when: false

- name: Display interface status
  ansible.builtin.debug:
    msg: |
      Network interfaces on {{ inventory_hostname }}:
      {{ interface_status.stdout }}

- name: Check bridge status
  ansible.builtin.command: ip -br link show type bridge
  register: bridge_status
  changed_when: false

- name: Display bridge status
  ansible.builtin.debug:
    msg: |
      Bridge status on {{ inventory_hostname }}:
      {{ bridge_status.stdout }}

- name: Verify SDN configuration exists
  ansible.builtin.command: pvesh get /cluster/sdn
  register: sdn_check
  changed_when: false
  ignore_errors: true

- name: Display SDN configuration status
  ansible.builtin.debug:
    msg: |
      SDN configuration on {{ inventory_hostname }}:
      {{ sdn_check.stdout | default('SDN not configured yet') }}

- name: Fail if critical connectivity issues detected
  ansible.builtin.fail:
    msg: "Critical connectivity issues detected. Check network configuration before proceeding to fabric finalization."
  when:
    - ping_results.failed | default(false)
    - not ansible_check_mode
