---
- name: Ensure app directory exists
  file:
    path: "/opt/{{ app_name }}"
    state: directory
    owner: root
    group: docker
    mode: "0750"

- name: Render config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0640') }}"
    owner: root
    group: docker
  loop: "{{ configs }}"
  when: configs | length > 0
  no_log: true

- name: Render docker-compose.yml
  template:
    src: "docker-compose.yml.j2"
    dest: "/opt/{{ app_name }}/docker-compose.yml"
    mode: "0644"
    owner: root
    group: docker

- name: Deploy app with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "/opt/{{ app_name }}"
    state: present
  when: not use_portainer

- name: Deploy app via Portainer API
  uri:
    url: "{{ portainer_url }}/api/endpoints/1/docker/compose"
    method: POST
    headers:
      Authorization: "Bearer {{ portainer_token }}"
    body_format: json
    body:
      StackFileContent: "{{ lookup('file', '/opt/' + app_name + '/docker-compose.yml') }}"
      Name: "{{ app_name }}"
  when: use_portainer
