---
# Dynamically fetch all secrets defined in vault_secrets
- name: Fetch secrets from Vault
  set_fact:
    "{{ item.key }}": "{{ lookup('community.hashi_vault.hashi_vault', 'secret=' + item.value + ' auth_method=approle role_id=' + vault_role_id + ' secret_id=' + vault_secret_id + ' url=' + vault_addr) }}"
  loop: "{{ vault_secrets | dict2items }}"
  no_log: true
