version: "3.9"
services:
  api:
    build: .
    environment:
      NODE_ENV: production
      PORT: 3001
    ports: ["3001:3001"]
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports: ["11434:11434"]
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    ports: ["3002:8080"]
    depends_on: ["ollama"]
