

# Main orchestration for Docker overlay network probing

- name: Include DPI monitor setup role
	import_role:
		name: dpi_monitor_setup

- name: Discover Docker networks and connected containers
	include_tasks: docker-network-discover.yml

- name: Mirror Docker network bridges to DPI veth
	include_tasks: docker-network-mirror.yml
	loop: "{{ docker_bridges }}"
	loop_control:
		loop_var: docker_bridge
