
# TODO: Integrate with edgesec-REST API for VM NIC provisioning
# TODO: Integrate with Netbox for VM NIC registration
# TODO: Integrate with Datto RMM for VM NIC device onboarding
# roles/vm_nic/tasks/main.yml

- name: Attach VM NICs using Proxmox API
  community.general.proxmox:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    node: "{{ inventory_hostname }}"
    vmid: "{{ item.vmid }}"
    netif:
      - bridge: "{{ item.bridge }}"
        model: virtio
        tag: "{{ item.vlan_tag | default(omit) }}"
  loop: "{{ vm_nic_map }}"
  tags:
    - vm_nic
    - verify_vm_nic
