---
- name: Install prerequisite packages (Debian/Ubuntu)
  apt:
    name: "{{ prereq_packages }}"
    state: present
    update_cache: yes
  become: true

- name: Download pve-network-interface-pinning if URL provided
  get_url:
    url: "{{ pve_network_interface_pinning_url }}"
    dest: "{{ pve_network_interface_pinning_path }}"
    mode: '0755'
  when: pve_network_interface_pinning_url is defined and pve_network_interface_pinning_url | length > 0
  become: true

- name: Ensure pve-network-interface-pinning is executable
  file:
    path: "{{ pve_network_interface_pinning_path }}"
    mode: '0755'
    state: file
  when: pve_network_interface_pinning_url is defined and pve_network_interface_pinning_url | length > 0
  become: true
